name: busino
description: "Busino - Smart Urban Bus Reservation App (Passenger)"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Navigation
  go_router: ^14.6.2

  # Dependency Injection
  get_it: ^8.0.3

  # Functional Programming (Either, Option)
  dartz: ^0.10.1

  # Local Database
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5

  # GPS & Location
  geolocator: ^14.0.3
  geocoding: ^5.0.0
  permission_handler: ^13.0.2

  # UI & Utils
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  intl: ^0.20.2
  uuid: ^4.5.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-Bold.ttf
          weight: 700